// <auto-generated />
using HotelBooking.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelBooking.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220310130123_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelBooking.Core.Data.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HotelId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HotelDescription")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("HotelDescription");

                    b.Property<double>("HotelDiscount")
                        .HasColumnType("float")
                        .HasColumnName("HotelDiscount");

                    b.Property<string>("HotelImage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("HotelImage");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HotelName");

                    b.Property<double>("HotelPrice")
                        .HasColumnType("float")
                        .HasColumnName("HotelPrice");

                    b.Property<double>("HotelRank")
                        .HasColumnType("float")
                        .HasColumnName("HotelRank");

                    b.HasKey("HotelId");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            HotelDescription = "Stay at Mövenpick Hotel Amman to benefit from a great location, excellent food and wonderful Jordanian hospitality.  ",
                            HotelDiscount = 3.0,
                            HotelImage = "https://cdn.audleytravel.com/700/-/79/154043075198089103191054060164068041221090238072.jpg",
                            HotelName = "movenpick",
                            HotelPrice = 35.0,
                            HotelRank = 6.0
                        },
                        new
                        {
                            HotelId = 2,
                            HotelDescription = "Stay at the Crowne Plaza Hotel Amman to take advantage of the great location, excellent food and wonderful Jordanian hospitality. ",
                            HotelDiscount = 9.0,
                            HotelImage = "https://pix10.agoda.net/hotelImages/293/293138/293138_14040916380019019069.jpg",
                            HotelName = "Crowne Plaza",
                            HotelPrice = 45.0,
                            HotelRank = 7.0
                        },
                        new
                        {
                            HotelId = 3,
                            HotelDescription = "Thousand Nights is planned to be fully self-sufficient from an infrastructure point of view, providing a diverse range of integrated services that span roads, electrical grids, ",
                            HotelDiscount = 11.0,
                            HotelImage = "https://imagesawe.s3.amazonaws.com/companies/images/2019/12/thousand_nights_hotel.jpg",
                            HotelName = "Thousand Nights",
                            HotelPrice = 65.0,
                            HotelRank = 7.0
                        },
                        new
                        {
                            HotelId = 4,
                            HotelDescription = "holiday inn is planned to be fully self-sufficient from an infrastructure point of view, providing a diverse range of integrated services that span roads, electrical grids, ",
                            HotelDiscount = 12.0,
                            HotelImage = "https://www.bridgetravel.com.jo/uploads/0000/15/2019/10/17/gallery-8-file-69.jpg",
                            HotelName = "holiday inn",
                            HotelPrice = 77.0,
                            HotelRank = 7.0
                        },
                        new
                        {
                            HotelId = 5,
                            HotelDescription = "An iconic landmark in bustling Amman, InterContinental Jordan Hotel offers cosmopolitan amenities with a Middle Eastern touch, from light-filled rooms, vibrant furnishings and sweeping architecture to international cuisines, Spa facilities, a selection of beautiful spaces suitable for different occasions, along with magnificent views. Located atop one of the seven hills of Amman, the hotel attracts international clientele from all over the world who enjoy its close proximity to the city center.",
                            HotelDiscount = 14.0,
                            HotelImage = "https://media.cntraveler.com/photos/5440499858544c134c067b02/16:9/w_2560,c_limit/intercontinental-amman-jordan-exterior-rca-2014.jpg",
                            HotelName = "intercontinental",
                            HotelPrice = 67.0,
                            HotelRank = 4.0
                        },
                        new
                        {
                            HotelId = 6,
                            HotelDescription = "A stay at Corp Amman Hotel places you in the heart of Amman, within a 5-minute drive of The Specialty Hospital and Al Abdali Mall. This 4.5-star hotel is 1.6 mi (2.5 km) from The Boulevard and 2.2 mi (3.6 km) from Amman Citadel. Make yourself at home in one of the 108 air-conditioned rooms featuring minibars and LCD televisions. Complimentary wireless Internet access keeps you connected, and cable programming is available for your entertainment.",
                            HotelDiscount = 22.0,
                            HotelImage = "https://media-cdn.tripadvisor.com/media/photo-s/10/8f/a3/4e/corp-amman-hotel.jpg",
                            HotelName = "Corp",
                            HotelPrice = 79.0,
                            HotelRank = 6.0
                        },
                        new
                        {
                            HotelId = 7,
                            HotelDescription = "One of our top picks in Amman.This hotel is located in Shmeisani, Amman’s central business district. It features a 24-hour gym, a spa and 3 restaurants. The rooms offer panoramic Amman city views. The modern rooms at the Kempinski Hotel Amman have a seating area, a pillow menu and a marble bathroom with luxury amenities. Some rooms include a separate living area, an LCD TV and access to the Executive Lounge.",
                            HotelDiscount = 9.0,
                            HotelImage = "http://fstravels.com/cp/pictures/hotels/top/453_Kempinski-Hotel-Amman-Jordan.JPG",
                            HotelName = "Kempinski",
                            HotelPrice = 49.0,
                            HotelRank = 6.0
                        },
                        new
                        {
                            HotelId = 8,
                            HotelDescription = "At the heart of the city, where modern and historic Amman meet, atop one of the city’s most prominent seven hills, Grand Hyatt Amman stands out with its distinctive carved pink stone façade, offering sweeping 360-degree views of the city. From welcoming guests and travelers into our expansive lobby, to not only capturing five-star comfort, but also an abundance of award-winning dining experiences, you will find all of this and more at Grand Hyatt Amman.",
                            HotelDiscount = 9.0,
                            HotelImage = "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2017/08/14/1619/Grand-Hyatt-Amman-P207-Exterior-Night.jpg/Grand-Hyatt-Amman-P207-Exterior-Night.16x9.jpg",
                            HotelName = "Grand Hyatt Amman",
                            HotelPrice = 49.0,
                            HotelRank = 7.0
                        },
                        new
                        {
                            HotelId = 9,
                            HotelDescription = "Toledo Amman Hotel is situated in the heart of Amman, on the edge of the old city center and within walking distance to the new downtown. Toledo Amman Hotel is only few minutes away from major historical and biblical sites, in addition only a two minute walk to the future entertainment center 'Al Abdali Boulevard'.",
                            HotelDiscount = 9.0,
                            HotelImage = "https://www.toledohotel.jo/content/images/thumbs/0000489_exterior.jpeg",
                            HotelName = "Toledo Amman Hotel",
                            HotelPrice = 49.0,
                            HotelRank = 4.0
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Data.HotelAddress", b =>
                {
                    b.Property<int>("HotelAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HotelAddressId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HotelAddressCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("HotelAddressCity");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.HasKey("HotelAddressId");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelAddress");

                    b.HasData(
                        new
                        {
                            HotelAddressId = 1,
                            HotelAddressCity = "Amman",
                            HotelId = 1
                        },
                        new
                        {
                            HotelAddressId = 2,
                            HotelAddressCity = "Aqaba",
                            HotelId = 1
                        },
                        new
                        {
                            HotelAddressId = 3,
                            HotelAddressCity = "Dead Sea",
                            HotelId = 1
                        },
                        new
                        {
                            HotelAddressId = 4,
                            HotelAddressCity = "Amman",
                            HotelId = 2
                        },
                        new
                        {
                            HotelAddressId = 5,
                            HotelAddressCity = "Aqaba",
                            HotelId = 2
                        },
                        new
                        {
                            HotelAddressId = 6,
                            HotelAddressCity = "Dead Sea",
                            HotelId = 4
                        },
                        new
                        {
                            HotelAddressId = 7,
                            HotelAddressCity = "Dead Sea",
                            HotelId = 3
                        },
                        new
                        {
                            HotelAddressId = 8,
                            HotelAddressCity = "Irbid",
                            HotelId = 3
                        },
                        new
                        {
                            HotelAddressId = 9,
                            HotelAddressCity = "Amman",
                            HotelId = 5
                        },
                        new
                        {
                            HotelAddressId = 10,
                            HotelAddressCity = "Aqaba",
                            HotelId = 5
                        },
                        new
                        {
                            HotelAddressId = 11,
                            HotelAddressCity = "Amman",
                            HotelId = 6
                        },
                        new
                        {
                            HotelAddressId = 12,
                            HotelAddressCity = "Irbid",
                            HotelId = 6
                        },
                        new
                        {
                            HotelAddressId = 13,
                            HotelAddressCity = "Dead Sea",
                            HotelId = 6
                        },
                        new
                        {
                            HotelAddressId = 14,
                            HotelAddressCity = "Amman",
                            HotelId = 7
                        },
                        new
                        {
                            HotelAddressId = 15,
                            HotelAddressCity = "Irbid",
                            HotelId = 7
                        },
                        new
                        {
                            HotelAddressId = 16,
                            HotelAddressCity = "Aqaba",
                            HotelId = 7
                        },
                        new
                        {
                            HotelAddressId = 17,
                            HotelAddressCity = "Amman",
                            HotelId = 8
                        },
                        new
                        {
                            HotelAddressId = 18,
                            HotelAddressCity = "Aqaba",
                            HotelId = 8
                        },
                        new
                        {
                            HotelAddressId = 19,
                            HotelAddressCity = "Irbid",
                            HotelId = 9
                        },
                        new
                        {
                            HotelAddressId = 20,
                            HotelAddressCity = "Dead Sea",
                            HotelId = 9
                        },
                        new
                        {
                            HotelAddressId = 21,
                            HotelAddressCity = "Amman",
                            HotelId = 9
                        },
                        new
                        {
                            HotelAddressId = 22,
                            HotelAddressCity = "Petra",
                            HotelId = 9
                        });
                });

            modelBuilder.Entity("HotelBooking.Core.Data.HotelAddress", b =>
                {
                    b.HasOne("HotelBooking.Core.Data.Hotel", "Hotel")
                        .WithMany("HotelAddresses")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelBooking.Core.Data.Hotel", b =>
                {
                    b.Navigation("HotelAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
